# Generated by Django 3.1.5 on 2021-01-14 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card',
            field=models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Номер карты'),
        ),
    ]
