# Generated by Django 3.1.5 on 2021-01-15 06:57

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20210114_2043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created'], 'verbose_name': 'Бонусный Аккаунт', 'verbose_name_plural': 'Бонусные Аккаунты'},
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Введите количество баллов', max_digits=7, max_length=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Бонусный баланс'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('money', 'Money'), ('add_bonus', 'Add Bonus'), ('substract_bonus', 'Substract Bonus')], default='money', help_text='Выберите тип', max_length=30, verbose_name='Тип')),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Введите сумму', max_digits=7, max_length=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Сумма')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('account', models.ForeignKey(help_text='Выберите бонусный аккаунт', on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.account', verbose_name='Аккаунт')),
            ],
            options={
                'verbose_name': 'Транзакция',
                'verbose_name_plural': 'Транзакции',
                'ordering': ['-date'],
            },
        ),
    ]
