# Generated by Django 3.1.5 on 2021-01-14 16:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210114_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='card',
            field=models.CharField(max_length=12, unique=True, validators=[django.core.validators.RegexValidator(message='Номер карты должен состоять из 12-ти цифр 0-9', regex='^[0-9]{12}$')], verbose_name='Номер карты'),
        ),
        migrations.AlterField(
            model_name='account',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='account',
            name='surname',
            field=models.CharField(db_index=True, max_length=150, verbose_name='Фамилия'),
        ),
        migrations.AlterIndexTogether(
            name='account',
            index_together=set(),
        ),
    ]
