# Generated by Django 3.1.5 on 2021-01-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20210114_1942'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, max_length=12, verbose_name='Бонусный баланс'),
            preserve_default=False,
        ),
    ]
